version: '3.8'

services:
  vue-build-customer:
    image: customer-w-list-image
    container_name: customer-w-list-container
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app # Монтируем текущую директорию в контейнер
    command: sh -c "npm install && npm run build" # Устанавливаем зависимости и запускаем сборку приложения
    restart: "no" # Не перезапускаем после завершения сборки
